services:
  - type: web
    name: taskflow-api
    runtime: python
    plan: free
    repo: https://github.com/zxDOOMxz/TaskFlow.git
    branch: master
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_ENABLED
        value: "true"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: MINIO_ENDPOINT
        value: minio:9000
      - key: MINIO_ACCESS_KEY
        value: minioadmin
      - key: MINIO_SECRET_KEY
        value: minioadmin
      - key: MINIO_BUCKET
        value: taskflow
